version: '3.5'

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
  redis-data:

services:
  ### PHP-FPM ##############################################
  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
    volumes:
      - ./docker/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    ports:
      - "${PHP_FPM_XDEBUG_PORT:-9003}:9003"
    expose:
      - "${NGINX_PHP_UPSTREAM_PORT:-9000}"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy

  ### Nginx ###########################################
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
      - "${NGINX_HOST_HTTPS_PORT:-443}:443"
    depends_on:
      - php-fpm
    networks:
      - backend

  ### MySQL ###########################################
  mysql:
    build:
      context: ./docker/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 15s
      timeout: 5s
      retries: 5

  ### PHPMyAdmin ###########################################
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
      - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy

  ### Redis ################################################
  redis:
    build:
      context: ./docker/redis
      args:
        REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - backend